@startuml io

title = pdtable.io detailed API

skinparam {
    ArrowFontName Consolas
}

left to right direction

rectangle files as "File / stream" #WhiteSmoke {
    file csv as "<b>StarTable CSV"
    file xl as "<b>StarTable\n<b>Excel workbook\n(file only)"
    file json as "JSON"
}

rectangle memory as "Memory" #WhiteSmoke {
    file table as "==Table"
    file cellgrid as "Raw cell grid" #LightGray
    file prejson as "JsonDataPrecursor" #LightGray
    file jsondata as "JsonData"
}

csv --> cellgrid : <b>read_csv()
xl --> cellgrid : <b>read_excel()

cellgrid -> prejson
prejson -> jsondata : to='jsondata'
prejson --> table : <b>to='pdtable'\n<b>(default)

json ..> jsondata : json.load()
jsondata ..> json : json.dump()

jsondata --> table : json_data_to_table()
jsondata <-- table : table_to_json_data()

csv <-- table #Gray : <b>write_csv()
xl <-- table #Gray : <b>write_excel()

@enduml
