@startuml IO

title = pdtable.io highlights

skinparam {
    Arrow {
        FontName Consolas
    }
}

left to right direction

rectangle files as "File / stream" {
    file csv as "<b>CSV"
    file xl as "<b>Excel"
    file json as "JSON"
}

rectangle memory as "Memory" {
    file cellgrid as "Cell grid" #LightGray
    file prejson as "JsonDataPrecursor" #LightGray
    file jsondata as "JsonData"
    file table as "<b>Table"
}

csv --> cellgrid : <b>read_csv()
xl --> cellgrid : <b>read_excel()

cellgrid -->prejson
prejson -> jsondata : to='jsondata'
prejson --> table : <b>to='pdtable'\n<b>(default)

json --> jsondata : json.load()
jsondata --> json : json.dump()

jsondata --> table : json_data_to_table()
jsondata <-- table : table_to_json_data()

csv <--table : <b>write_csv()
xl <--table : <b>write_excel()

@enduml
